### ISSUE TITLE
createWithClient example

### ISSUE THREAD

**Issue by mtuchi** [graphaware/reco4php#19]
Am using laravel to test this framework and am getting 

> ClientErrorException in ErrorPlugin.php line 46:
Unauthorized

I was wondering if there is example where i can use 

> RecommenderService::createWithClient(...);

Instead of 

> RecommenderService::create($databaseUri);

**Comment by drjonnicholson** [comment]
We are thinking of using this in a Laravel application, did you get the library to work in Laravel?

**Comment by ikwattro** [comment]
@drjonnicholson Nothing should prevent this library to run in laravel. There is not dependency on any framework.
