### ISSUE TITLE
How to import users and items using PHP?

### ISSUE THREAD

**Issue by elfeffe** [graphaware/reco4php#20]
In testing it's ok to import it manually, but how to import and update data automatically with code?

**Comment by ikwattro** [comment]
Can you elaborate a bit more your question ?

**Comment by elfeffe** [comment]
The documentation shows how to import the CSV using Cypher 

> LOAD CSV WITH HEADERS FROM "file:///Users/ikwattro/dev/movielens/movies.csv" AS row
> WITH row
> MERGE (movie:Movie {id: toInt(row.movieId)})
> ON CREATE SET movie.title = row.title
> WITH movie, row
> UNWIND split(row.genres, '|') as genre
> MERGE (g:Genre {name: genre})
> MERGE (movie)-[:HAS_GENRE]->(g)

This is not very clear that you can do the same using a normal "insert", I got confused because other systems use some API for inserts, but this is a normal insert or save in Neo4j

**Comment by ikwattro** [comment]
Doing continuous imports of new data can be done with plain cypher using only the [driver](https://github.com/graphaware/neo4j-php-client) . You will have to code it depending your domain.
