### ISSUE TITLE
Implement Blacklist

### ISSUE THREAD

**Issue by rubenvandeven** [graphaware/reco4php#7]
It seems the blacklists can be defined in `RecommendationEngine::blacklistBuilders()`, these get loaded by the `BaseRecommendationEngine::buildBlackListBuilders()`.
However, it seems the blacklists are then not executed so all results still include blacklisted items.
Is it so that this feature is not implemented yet? Even though it is included in the documentation & examples.

Thank you!

**Comment by ikwattro** [comment]
True, this is planned to be pushed this evening.

I'll keep posted here on the status.

**Comment by ikwattro** [comment]
@rubenvandeven bd5aada87ea0c73ffcbceb4087059588a88948b5

I'll tag a new release tonight

**Comment by ikwattro** [comment]
@rubenvandeven Let's continue the discussion here about the composer issue.

What I would think : 

* Don't put min stability to dev but require alpha packages explicitly
* Remove composer.lock before updating the packages

**Comment by ikwattro** [comment]
@rubenvandeven What's your status now with this issue ?

**Comment by rubenvandeven** [comment]
Sorry, I have not worked with it for the last weeks. The last solution was to explicitly require the alpha version of the client package.

Requiring min stability alpha might fix it - it was set to dev for an earlier version of reco4php & client. However, I cannot try this before next week. I will keep you posted on it!

**Comment by ikwattro** [comment]
Cool, I'll close this issue. Please open a new one if you still have problems with composer
